import { useState } from "react";
import { useNavigate } from "react-router";
import { RescuerDashboard } from "../components/RescuerDashboard";
import { RescuerAuth } from "../components/RescuerAuth";
import { useData } from "../context/DataContext";
import { SupabaseService, supabase } from "../services/SupabaseService";
import { RescuerAccount } from "../App";
import { projectId, publicAnonKey } from "../utils/supabase/info";

const SERVER_URL = `https://${projectId}.supabase.co/functions/v1/make-server-12d090c6`;

export function RescuerPage() {
  const navigate = useNavigate();
  const { rescueRequests, updateRequestStatus, rescuers } = useData();
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [currentRescuer, setCurrentRescuer] = useState<{
    name: string;
    email: string;
    id: string;
    displayId: string;
  } | null>(null);

  const handleBack = () => {
    if (isAuthenticated) {
      setIsAuthenticated(false);
      setCurrentRescuer(null);
      supabase.auth.signOut();
    } else {
      navigate("/");
    }
  };

  const handleLogin = async (identifier: string, password: string) => {
    try {
      const { data, error } = await supabase.auth.signInWithPassword({
        email: identifier,
        password: password,
      });

      if (error) {
        return { success: false, error: error.message };
      }

      if (data.user) {
        // Find rescuer profile in our data context
        // We might need to refresh data first
        const rescuer = rescuers.find(r => r.id === data.user!.id);
        
        if (rescuer) {
          setIsAuthenticated(true);
          setCurrentRescuer({
            name: rescuer.name || '',
            email: rescuer.email,
            id: rescuer.id,
            displayId: rescuer.displayId || ''
          });
          return { success: true, name: rescuer.name };
        } else {
             // Fallback: fetch directly if context is stale
             const rescuerResponse = await fetch(`${SERVER_URL}/rescuers`, {
                headers: { 'Authorization': `Bearer ${publicAnonKey}` }
            });
            const allRescuers: RescuerAccount[] = await rescuerResponse.json();
            const found = allRescuers.find(r => r.id === data.user!.id);

            if (found) {
                setIsAuthenticated(true);
                setCurrentRescuer({
                  name: found.name || '',
                  email: found.email,
                  id: found.id,
                  displayId: found.displayId || ''
                });
                return { success: true, name: found.name };
            }
        }
        return { success: false, error: 'Rescuer profile not found' };
      }
      return { success: false, error: 'Login failed' };
    } catch (err) {
      console.error('Login error:', err);
      return { success: false, error: 'Network error' };
    }
  };

  const handleRegister = async (email: string, password: string, name: string, phone: string, address: string) => {
     // Use the new service that writes to 'rescuer_registration' table
     const { error } = await SupabaseService.registerRescuer({
         email,
         password,
         name,
         phone,
         address,
         // id is generated by backend/db
     });

     if (error) {
         return { success: false, error: typeof error === 'string' ? error : error.message };
     }
     return { success: true };
  };

  if (!isAuthenticated) {
    return (
      <RescuerAuth
        onLogin={handleLogin}
        onRegister={handleRegister}
        onBack={handleBack}
      />
    );
  }

  return (
    <RescuerDashboard
      onBack={handleBack}
      requests={rescueRequests}
      onUpdateStatus={updateRequestStatus}
      rescuerName={currentRescuer?.name || ''}
      rescuerEmail={currentRescuer?.email || ''}
      rescuerId={currentRescuer?.id || ''}
      rescuerDisplayId={currentRescuer?.displayId || ''}
    />
  );
}
