/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sovnteqvfzdmktcwelus"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdm50ZXF2ZnpkbWt0Y3dlbHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MzE2NTcsImV4cCI6MjA4NjMwNzY1N30.pVjA0MRaiCD8t6iDBYB0Aeoi-__aM-Bos6INAkhnVn0"